### ISSUE TITLE
Deliver Document

### ISSUE THREAD

**Issue by gruo** [gruo/dt9837#1]
send mail of customer requirements specification

due date: **2018-01-12, 12:00**

**Comment by JRichter96** [comment]
[customer_requirements_specification.zip](https://github.com/gruo/dt9837/files/1611023/customer_requirements_specification.zip)

Englisches Dokument, Formatierung wegen MS Word verhauen

**Comment by gruo** [comment]
[customer_requirements_specification.pdf](https://github.com/gruo/dt9837/files/1611031/customer_requirements_specification.pdf)

final version, review ( #2 ) missing

**Comment by gruo** [comment]
mail is sent
