### ISSUE TITLE
switch license to GPL

### ISSUE THREAD

**Issue by gruo** [gruo/dt9837#15]
kernel modules using the USB subsystem require a version of this license

**Comment by gruo** [comment]
the license was changed and is shown correctly on github

**Comment by amitashkenazi** [comment]
Hi,
I have an issue with the driver.
Following the INSTALL instruction, I can not get /dev/comedi0 one the dt9837B is pluged to my machine.
The output of `cat /proc/comedi` is as follow:

comedi version 0.7.76.1
format string: "%2d: %-20s %-20s %4d", i, driver_name, board_name, n_subdevices
no devices
dt9837:
 dt9837
