### ISSUE TITLE
Requirements Review

### ISSUE THREAD

**Issue by gruo** [gruo/dt9837#2]
pass customer requirements specification to technical contact for review

**Comment by gruo** [comment]
mail sent

**Comment by JRichter96** [comment]
Answer:

ein freundliches Hallo in die Runde,

ich lese mir das Lastenheft heute Abend durch. Gegebenenfalls müsste ich in den
nächsten Tagen noch weitere Spezifikationen konsultieren.

Für den Kontakt zu MeasurementComputing (Eigentümer von DataTranslation) kann ich
Ihnen Hilfe anbieten, auch für die Betreuung und Evaluierung. Ob das eine
Rechtfertigung zur Nennung meines Namens darstellt, da habe ich Zweifel.

Ich freue mich, das Sie das Projekt übernehmen.

mit freundlichen Grüßen von unterwegs
Thomas Fischer


Phone: +49.151.56075992

**Comment by gruo** [comment]
closed as no changes nor additions were requested.
