### ISSUE TITLE
Set up virtual machine (Linux)

### ISSUE THREAD

**Issue by JRichter96** [gruo/dt9837#6]

**Comment by gruo** [comment]
- [ ] download linux kernel sources
- [ ] install development tools
- [ ] successfully build a kernel module (simple sample or existing one)

**Comment by JRichter96** [comment]
virtual mashine set up.
Got internet connection now.

**Comment by JRichter96** [comment]
Debian updated, current version: 4.9.30

**Comment by JRichter96** [comment]
cant install development tools yet - os tells me to insert a dvd.

command used: apt-get install dpkg-dev (as root)

**Comment by JRichter96** [comment]
Virtual mashine fully installed now.

**Comment by JRichter96** [comment]
Closing issue now, can be opened later, if any problems occur.
